global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Based on: https://github.com/prometheus/prometheus/blob/release-2.43/documentation/examples/prometheus-eureka.yml
# Based on: https://github.dev/barrycommins/prometheus-eureka-spring-boot-demo
scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /metrics
    static_configs:
      - targets: ['%%PROMETHEUS_HOSTNAME%%:%%PROMETHEUS_PORT%%']
        labels:
          application: 'PROMETHEUS'

  - job_name: 'discovery_server_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          [
            '%%DISCOVERY_SERVER_SERVICE_HOSTNAME%%:%%DISCOVERY_SERVER_SERVICE_CONTAINER_PORT%%',
          ]
        labels:
          application: 'DISCOVERY-SERVER-SERVICE'

  - job_name: 'eureka'
    eureka_sd_configs:
      - server: http://%%EUREKA_HOSTNAME%%:%%EUREKA_PORT%%/eureka
        basic_auth:
          username: %%EUREKA_SECURITY_USERNAME%%
          password: %%EUREKA_SECURITY_PASSWORD%%
    relabel_configs:
      - source_labels: [__meta_eureka_app_name]
        target_label: application

      # "prometheus.scrape = true" metadata.
      - source_labels: [__meta_eureka_app_instance_metadata_prometheus_scrape]
        action: keep
        regex: true

      # "prometheus.path = <metric path>" annotation.
      - source_labels: [__meta_eureka_app_instance_metadata_prometheus_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)

      # based on application "prometheus.port = <port>" metadata.
      # - source_labels:
      #     [__address__, __meta_eureka_app_instance_metadata_prometheus_port]
      #   action: replace
      #   regex: ([^:]+)(?::\d+)?;(\d+)
      #   replacement: $1:$2
      #   target_label: __address_
