# syntax=docker/dockerfile:1.3.0-labs

FROM eclipse-temurin:17-jdk-focal

RUN --mount=type=cache,target=/var/cache/apt \
  apt-get update && \
  apt-get --no-install-recommends install -y gosu

ARG service_folder_name
ARG username
ARG useruid
ARG usergid

RUN groupadd --force -g $usergid $username && \
  useradd -ms /bin/bash --no-user-group -u $useruid -g $usergid $username && \
  usermod -u $useruid $username

RUN mkdir -p /app /home/$username/.m2/wrapper /home/$username/.m2/repository && \
  chown -R $username:$username /app /home/$username/.m2/wrapper /home/$username/.m2/repository

WORKDIR /app

COPY --chown=$username:$username ./pom.xml ./mvnw ./.env ./
COPY --chown=$username:$username ./.mvn/ ./.mvn
COPY --chown=$username:$username ./common/pom.xml ./common/
COPY --chown=$username:$username ./inventory-service/pom.xml ./inventory-service/
COPY --chown=$username:$username ./product-service/pom.xml ./product-service/
COPY --chown=$username:$username ./order-service/pom.xml ./order-service/

RUN --mount=type=cache,target=/home/$username/.m2,uid=$useruid,gid=$usergid \
  gosu $username ./mvnw -am -pl $service_folder_name -e dependency:go-offline

COPY --chown=$username:$username ./$service_folder_name/target ./$service_folder_name/target

USER $username

ENV SERVICE_FOLDER_NAME ${service_folder_name}

CMD ./mvnw -am -pl ${SERVICE_FOLDER_NAME} -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005" spring-boot:run