# syntax=docker/dockerfile:1.3.0-labs

FROM eclipse-temurin:17-jdk-focal

RUN apt-get update && \
  apt-get install gosu -y

ARG service_folder_name
ARG username
ARG useruid
ARG usergid

RUN groupadd --force -g $usergid $username && \
  useradd -ms /bin/bash --no-user-group -u $useruid -g $usergid $username && \
  usermod -u $useruid $username

RUN mkdir -p /app /home/$username/.m2/wrapper /home/$username/.m2/repository && \
  chown -R $username:$username /app /home/$username/.m2/wrapper /home/$username/.m2/repository

WORKDIR /app

COPY --chown=$username:$username ./pom.xml ./mvnw ./.env ./
COPY --chown=$username:$username ./.mvn/ ./.mvn
COPY --chown=$username:$username ./$service_folder_name/pom.xml ./$service_folder_name/

RUN --mount=type=cache,target=/home/$username/.m2,uid=$useruid,gid=$usergid \
  gosu $username ./mvnw -f ./$service_folder_name/pom.xml -e dependency:go-offline

COPY --chown=$username:$username ./$service_folder_name/src ./$service_folder_name/src

USER $username

ENV SERVICE_FOLDER_NAME ${service_folder_name}

CMD ./mvnw -f ./${SERVICE_FOLDER_NAME}/pom.xml -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005" spring-boot:run