server:
  http_listen_address: 0.0.0.0
  http_listen_port: ${TEMPO_PORT}

distributor:
  receivers:
    zipkin:
      endpoint: 0.0.0.0:${ZIPKIN_PORT}

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks
