apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    id: 1
    uid: dnjtIyP4k
    orgId: 1
    access: proxy
    url: http://$PROMETHEUS_HOSTNAME:$PROMETHEUS_PORT
    basicAuth: false
    isDefault: true
    readOnly: false
    jsonData:
      httpMethod: POST
  - name: Loki
    type: loki
    id: 2
    uid: wf_mYlEVk
    orgId: 1
    url: http://$LOKI_HOSTNAME:$LOKI_PORT
    basicAuth: false
    isDefault: false
    readOnly: false
