apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    id: 1
    uid: dnjtIyP4k
    orgId: 1
    access: proxy
    url: http://$PROMETHEUS_HOSTNAME:$PROMETHEUS_PORT
    basicAuth: false
    isDefault: true
    readOnly: false
    jsonData:
      httpMethod: POST
